# Generated by Django 3.0.8 on 2021-03-13 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nip_number', models.IntegerField(blank=True, default=0, verbose_name='NIP number')),
                ('phone_number', models.IntegerField(blank=True, default=0, verbose_name='Phone number')),
                ('delivery_address', models.CharField(blank=True, default='0', max_length=100, verbose_name='Delivery address')),
                ('bank_account_number', models.IntegerField(blank=True, default=0, verbose_name='Bank account')),
            ],
        ),
    ]
